AWSTemplateFormatVersion: 2010-09-09
Description: Firewall policy deployment

Parameters:
  pEnvironment:
    Description: 'Environment'
    Type: String
    AllowedValues:
      - prd
      - tst
      - dev

  pBlacklistIPSetName:
    Description: Blacklist IP Set Name
    Type: String
    Default: cf-blacklist-ip-set
  
  pCustomRuleGroupName:
    Description: Mandatory Rule Group
    Type: String
    Default: fms-cf-mandatory-rule-group

  pEnableSampleRequest:
    Description: Sampled Request enabled?
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  pEnableCloudWatchMetrics:
    Description: CloudWatch metrics enabled?
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  pEnableRemediation:
    Description: Enable FMS Policy remediation?
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  
  pOverrideAction:
    Description: Override rules in the rule groups
    Type: String
    Default: "COUNT"

  pEnableResourceCleanUp:
    Description: Indicates whether FMS should automatically remove protections from resources that leave the policy scope and clean up resources that Firewall Manager is managing for accounts when those accounts leave policy scope.
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  pIncludeSpecificAccounts:
    Description: A comma separated list of specific accounts that need to be included to deploy FMS policy
    Type: String
    Default: ""

  pIncludeSpecificOrgUnits:
    Description: A comma separated list of specific org units that need to be included to deploy FMS policy
    Type: String
    Default: ""
  
  pRateLimit:
   Description: Rate limit that you want to keep
   Type: Number
   Default: 1000


Conditions:
  IncludeAllAccountsInMainOrg: !And [!Equals [!Ref pIncludeSpecificAccounts, ""], !Equals [!Ref pIncludeSpecificOrgUnits, ""]]
  IsSpecificAccountNull: !Equals [!Ref pIncludeSpecificAccounts, ""]
  IsSpecificOrgNull: !Equals [!Ref pIncludeSpecificOrgUnits, ""]

Resources:
  IPSetBlacklist: 
    Type: AWS::WAFv2::IPSet
    Properties: 
        Name: !Ref pBlacklistIPSetName
        Scope: CLOUDFRONT
        IPAddressVersion: IPV4
        Addresses: []

  # Custom rule group
  FMSCFCustomRuleGroup:
    Type: AWS::WAFv2::RuleGroup
    Properties:
        Name: !Ref pCustomRuleGroupName
        Scope: CLOUDFRONT
        VisibilityConfig:
            SampledRequestsEnabled: !Ref pEnableSampleRequest
            CloudWatchMetricsEnabled: !Ref pEnableCloudWatchMetrics
            MetricName: !Sub ${pCustomRuleGroupName}-metric     
        Capacity: 45
        Rules:
        - Name: prevent-xss-rule
          Priority: 0
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: !Ref pEnableSampleRequest
            CloudWatchMetricsEnabled: !Ref pEnableCloudWatchMetrics
            MetricName: prevent-xss-rule-metric
          Statement:
              XssMatchStatement:
                FieldToMatch:
                  QueryString: {}
                TextTransformations:
                  - Priority: 0
                    Type: NONE          
        - Name: ipblock-rule
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: !Ref pEnableSampleRequest
            CloudWatchMetricsEnabled: !Ref pEnableCloudWatchMetrics
            MetricName: ipblock-rule-metric
          Statement:
              IPSetReferenceStatement:
                Arn: !GetAtt IPSetBlacklist.Arn
        - Name: rate-based-rule
          Priority: 2
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: !Ref pEnableSampleRequest
            CloudWatchMetricsEnabled: !Ref pEnableCloudWatchMetrics
            MetricName: rate-based-rule-metric
          Statement:
              RateBasedStatement:
                Limit: !Ref pRateLimit
                AggregateKeyType: IP

  WAFPolicy:
    Type: AWS::FMS::Policy
    DependsOn:
      - FMSCFCustomRuleGroup
    Properties:
      ExcludeResourceTags: false
      DeleteAllPolicyResources: true
      PolicyName: waf-cloudfront-policy
      RemediationEnabled: !Ref pEnableRemediation
      ResourceType: 'AWS::CloudFront::Distribution'
      ResourcesCleanUp: !Ref pEnableResourceCleanUp
      IncludeMap:
        !If
          - IncludeAllAccountsInMainOrg
          - !Ref "AWS::NoValue"
          - 
            ACCOUNT: !If 
              - IsSpecificAccountNull 
              - !Ref "AWS::NoValue"
              - !Split [",", !Ref pIncludeSpecificAccounts]
            ORGUNIT: !If
              - IsSpecificOrgNull
              - !Ref "AWS::NoValue"
              - !Split [",", !Ref pIncludeSpecificOrgUnits]
      SecurityServicePolicyData:
        Type: WAFV2
        ManagedServiceData: !Sub '{"type":"WAFV2", 
                  "preProcessRuleGroups":
                  [
                    {
                      "ruleGroupArn":null,
                      "overrideAction":{"type":"${pOverrideAction}"},
                      "managedRuleGroupIdentifier":{"version":null,"vendorName":"AWS","managedRuleGroupName":"AWSManagedRulesCommonRuleSet"},
                      "ruleGroupType":"ManagedRuleGroup",
                      "excludeRules":[]
                    },
                    {
                      "ruleGroupArn":null,
                      "overrideAction":{"type":"${pOverrideAction}"},
                      "managedRuleGroupIdentifier":{"version":null,"vendorName":"AWS","managedRuleGroupName":"AWSManagedRulesLinuxRuleSet"},
                      "ruleGroupType":"ManagedRuleGroup",
                      "excludeRules":[]
                    },
                    {
                      "ruleGroupArn":null,
                      "overrideAction":{"type":"${pOverrideAction}"},
                      "managedRuleGroupIdentifier":{"version":null,"vendorName":"AWS","managedRuleGroupName":"AWSManagedRulesSQLiRuleSet"},
                      "ruleGroupType":"ManagedRuleGroup",
                      "excludeRules":[]
                    },
                    {
                      "ruleGroupArn":null,
                      "overrideAction":{"type":"${pOverrideAction}"},
                      "managedRuleGroupIdentifier":{"version":null,"vendorName":"AWS","managedRuleGroupName":"AWSManagedRulesKnownBadInputsRuleSet"},
                      "ruleGroupType":"ManagedRuleGroup",
                      "excludeRules":[]
                    },
                    {
                      "ruleGroupArn":null,
                      "overrideAction":{"type":"${pOverrideAction}"},
                      "managedRuleGroupIdentifier":{"version":null,"vendorName":"AWS","managedRuleGroupName":"AWSManagedRulesAnonymousIpList"},
                      "ruleGroupType":"ManagedRuleGroup",
                      "excludeRules":[]
                    },
                    {
                      "ruleGroupArn":null,
                      "overrideAction":{"type":"${pOverrideAction}"},
                      "managedRuleGroupIdentifier":{"version":null,"vendorName":"AWS","managedRuleGroupName":"AWSManagedRulesAmazonIpReputationList"},
                      "ruleGroupType":"ManagedRuleGroup",
                      "excludeRules":[]
                    },                                                          
                    {
                      "ruleGroupType":"RuleGroup",
                      "ruleGroupArn":"${FMSCFCustomRuleGroup.Arn}",
                      "overrideAction":{"type":"${pOverrideAction}"}
                    }
                  ],
                  "defaultAction":{"type":"ALLOW"}}' 
      Tags:
        - Key: Environment
          Value: !Ref pEnvironment

Outputs:
  FMSPolicy:
    Description: "FMS Global policy"
    Value: !GetAtt  WAFPolicy.Arn

  CFIPSetBlackList:
    Description: "IP Black List set, add IPs you want to blacklist for CloudFront"
    Value: !GetAtt IPSetBlacklist.Arn

  WAFCustomRuleGroup:
    Description: "Rule groups that contain custom rules"
    Value: !GetAtt FMSCFCustomRuleGroup.Arn
